let buffsList = [
  {
    name: 'Attributes',
    buffs: [
      {
        name: 'Agility',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package.',
        prefix: '+',
        suffix: ' to agility attribute',
      },
      {
        name: 'Block Value',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45% to block value per package',
        prefix: '',
        suffix: '% to block value',
      },
      {
        name: 'Camouflage',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to Camouflage per package',
        prefix: '',
        suffix: ' to camouflage',
      },
      {
        name: 'Constitution',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package',
        prefix: '+',
        suffix: ' to constitution attribute',
      },
      {
        name: 'Detect Camouflage',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to Detect Camouflage per package',
        prefix: '',
        suffix: ' to Detect Camouflage',
      },
      {
        name: 'Evasion Value',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to evasion value per package',
        prefix: '',
        suffix: ' to evasion value',
      },
      {
        name: 'Luck',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package',
        prefix: '+',
        suffix: ' to luck attribute',
      },
      {
        name: 'Precision',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package.',
        prefix: '+',
        suffix: ' to precision attribute',
      },
      {
        name: 'Stamina',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package.',
        prefix: '+',
        suffix: ' to stamina attribute',
      },
      {
        name: 'Strength',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45 to attribute per package.',
        prefix: '+',
        suffix: ' to strength attribute',
      },
      {
        name: 'Strikethrough Value',
        cost: 1,
        maxAssignments: 10,
        assignments: 0,
        effect: 45,
        description: '45% bonus per package to strikethrough value.',
        prefix: '',
        suffix: '% bonus to strikethrough value.',
      },
    ]
  },
  {
    name: 'Combat',
    buffs: [
      {
        name: 'Action Cost Reduction',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 9,
        description: '9% bonus per package in reducing all action costs',
        prefix: '',
        suffix: '% bonus in reducing all action costs',
      },
      {
        name: 'Block Chance',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to block chance',
        prefix: '',
        suffix: '% bonus to block chance',
      },
      {
        name: 'Critical Hit',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to critical hit chance',
        prefix: '',
        suffix: '% bonus to critical hit chance',
      },
      {
        name: 'Critical Hit Defense',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to critical hit defense',
        prefix: '',
        suffix: '% bonus to critical hit defense',
      },
      {
        name: 'Devastation',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% increase per package on the amount of devastation.',
        prefix: '+',
        suffix: ' increase to Devastation.',
      },
      {
        name: 'Dodge Chance',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to dodge chance',
        prefix: '',
        suffix: '% bonus to dodge chance',
      },
      {
        name: 'Evasion Chance',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to evasion chance',
        prefix: '',
        suffix: '% bonus to evasion chance',
      },
      {
        name: 'Glancing Blow Increased',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '+7 increase to Glancing Blow Increased per package.',
        prefix: '+',
        suffix: ' increase to Glancing Blow Increased.',
      },
      {
        name: 'Glancing Blow Melee',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '+7 increase to Glancing Blow Melee per package.',
        prefix: '+',
        suffix: ' increase to Glancing Blow melee.',
      },
      {
        name: 'Glancing Blow Ranged',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '+7 increase to Glancing Blow Ranged per package.',
        prefix: '+',
        suffix: ' increase to Glancing Blow Ranged.',
      },
      {
        name: 'Heal Potency',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 8,
        description: 'Increase the strength of your heals by 8% per package.',
        prefix: '+',
        suffix: ' increase to Heal Potency.',
      },
      {
        name: 'Parry Chance',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to parry',
        prefix: '',
        suffix: '% bonus to parry',
      },
      {
        name: 'Second Chance',
        cost: 2,
        maxAssignments: 4,
        assignments: 0,
        effect: 6,
        description: '6% chance per package to automatically heal damage when hit in combat.',
        prefix: '',
        suffix: '% chance to automatically heal damage when struck in combat.',
      },
      {
        name: 'Resilience',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 8,
        description: 'Reduce the amount of damage received by damage over time effects by 8% per package.',
        prefix: 'Damage received by damage over time effects reduced by ',
        suffix: '%',
      },
      {
        name: 'Strikethrough Chance',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 7,
        description: '7% bonus per package to strikethrough chance',
        prefix: '',
        suffix: '% bonus to strikethrough chance',
      },
    ]
  },
  {
    name: 'Miscellaneous',
    buffs: [
      {
        name: 'Flush With Success',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 3,
        description: '3% increase per package in the amount of experience earned.',
        prefix: '',
        suffix: '% increased experience gain.',
      },
      {
        name: 'Beast Experience',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 3,
        description: '3% increase per package in the amount of beast experience.',
        prefix: '+',
        suffix: ' increase to Beast Experience.',
      },
      {
        name: 'Go With The Flow',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 5,
        description: 'Increase all movement rates by 5% per package.',
        prefix: '',
        suffix: '% increase to all movement rates.',
      },
    ]
  },
  {
    name: 'Resistances',
    buffs: [
      {
        name: 'Elemental',
        cost: 1,
        maxAssignments: 5,
        assignments: 0,
        effect: 1800,
        description: '1800 to resistance per package',
        prefix: '',
        suffix: ' to resistance per package',
      },
      {
        name: 'Energy',
        cost: 1,
        maxAssignments: 5,
        assignments: 0,
        effect: 1800,
        description: '1800 to resistance per package',
        prefix: '+',
        suffix: ' to Energy protection.',
      },
      {
        name: 'Kinetic',
        cost: 1,
        maxAssignments: 5,
        assignments: 0,
        effect: 1800,
        description: '1800 to resistance per package',
        prefix: '+',
        suffix: ' to Kinetic protection.',
      },
    ]
  },
  {
    name: 'Trade',
    buffs: [
      {
        name: 'Amazing Success Chance',
        cost: 4,
        maxAssignments: 5,
        assignments: 0,
        effect: 0,
        description: 'Increase in Amazing Success Chance per package.',
        prefix: '',
        suffix: 'Increase in Amazing Success Chance.',
      },
      {
        name: 'Crafting Ground Assemblies',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 2,
        description: '2% increase per package on the amount of all ground crafting assemblies.',
        prefix: '+',
        suffix: ' increase to all Ground Crafting Assemblies.',
      },
      {
        name: 'Crafting Ground Experimentations',
        cost: 2,
        maxAssignments: 7,
        assignments: 0,
        effect: 2,
        description: '2% increase per package on the amount of all ground crafting experimentations.',
        prefix: '+',
        suffix: ' increase to all Ground Crafting Experimentations.',
      },
      {
        name: 'Crafting Space Assemblies',
        cost: 2,
        maxAssignments: 10,
        assignments: 0,
        effect: 50,
        description: '50% increase per package on the amount of all space crafting assemblies.',
        prefix: '+',
        suffix: ' increase to all Space Crafting Assemblies.',
      },
      {
        name: 'Crafting Space Experimentations',
        cost: 2,
        maxAssignments: 7,
        assignments: 0,
        effect: 2,
        description: '2% increase per package on the amount of all space crafting experimentations.',
        prefix: '+',
        suffix: ' increase to all Space Crafting Experimentations.',
      },
      {
        name: 'Creature Harvesting',
        cost: 4,
        maxAssignments: 2,
        assignments: 0,
        effect: 10,
        description: '10% increase per package on the amount of creature harvesting.',
        prefix: '+',
        suffix: ' increase to Creature Harvesting.',
      },
      {
        name: 'DNA Harvesting',
        cost: 5,
        maxAssignments: 10,
        assignments: 0,
        effect: 4,
        description: '4% increase per package on the amount of dna harvesting.',
        prefix: '+',
        suffix: ' increase to DNA Harvesting.',
      },
      {
        name: 'Factory Speed',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 0,
        description: 'Increase in Factory Speed per package.',
        prefix: '',
        suffix: 'Increase in Factory Speed.',
      },
      {
        name: 'Focused Enzyme Manipulation',
        cost: 4,
        maxAssignments: 10,
        assignments: 0,
        effect: 4,
        description: '4% increase per package on the amount of focused enzyme manipulation.',
        prefix: '+',
        suffix: ' increase to Focused Enzyme Manipulation.',
      },
      {
        name: 'Mutation Chance',
        cost: 5,
        maxAssignments: 2,
        assignments: 0,
        effect: 10,
        description: 'Increase chance of mutated a pet during incubation session by 10%.',
        prefix: 'Increase chance of mutated a pet during incubation session by ',
        suffix: '%.',
      },
      {
        name: 'Reverse Engineering Chance',
        cost: 2,
        maxAssignments: 5,
        assignments: 0,
        effect: 4,
        description: 'Increase strength of reverse engineering sessions by 4%.',
        prefix: 'Increase strength of reverse engineering sessions by ',
        suffix: '%.',
      },
    ]
  },
];

export default buffsList;
